name: Deploy Vite App to GH pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Create a .env file using values stored in the repo secrets
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_VITE_APPID: ${{ secrets.VITE_APPID }}
          envkey_VITE_PROJECTID: ${{ secrets.VITE_PROJECTID }}
          file_name: .env

      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
